#Numpy
Libreria que se especializa en claculos numéricos, util para trabajar con numeros y arrays. Permite trabajar más rápido.


*   Instalar -> pip install numpy
*   Usatr -> import numpy as np





In [2]:
#Importaciones necesarias
import numpy as np
import time

In [3]:
#Array 1 dimensión
array_1d = np.array([1,2,3,4,5,6,7,8,9,10])
type(array_1d)

numpy.ndarray

In [4]:
##Array 2 dimensión
array_2d = np.array([[9,10],[5,4],[3,8]])
array_2d

array([[ 9, 10],
       [ 5,  4],
       [ 3,  8]])

In [5]:
lista_notas = [[3,5,7], [2,9,3], [10,10,10]]
array_notas = np.array(lista_notas)
array_notas.shape

(3, 3)

In [6]:
#Array 3 dimensión
lista_de_listas3 = [[1,2,3],[4,5,6],[7,8,9],[10,10,10]]
array_3d = np.array(lista_de_listas3)
array_3d


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 10, 10]])

In [7]:
array_1d[-1]

np.int64(10)

In [8]:
array_2d[0]

array([ 9, 10])

In [9]:
#array[start:stop:step]
array_1d[0:4]

array([1, 2, 3, 4])

In [10]:
array_2d[0][0:-1]


array([9])

In [20]:
#array aleatorio, ideal para practicas
 #filas y columnas, o directamente una tabla si pongo.ej (5,4 ,3)

#array_aleatorio = np.random.rand(5,4)
#array_aleatorio = np.random.randint(10, size=(3,2)) #Similar
array_aleatorio = np.random.randint(1,10, (3,2))
array_aleatorio

array([[3, 2],
       [6, 7],
       [8, 5]])

In [28]:
array_aleatorio_1 = np.random.randint(0,10, (2,3))
array_aleatorio_2 = np.random.randint(0,10, (2,3))
print(array_aleatorio_1)
print("----------")
print(array_aleatorio_2)

[[2 9 0]
 [8 5 1]]
----------
[[9 8 5]
 [0 2 1]]


In [29]:
#Suma arrays aleatorio
suma_array = array_aleatorio_1 + array_aleatorio_2
suma_array

array([[11, 17,  5],
       [ 8,  7,  2]])

In [30]:
#Suma con metodo (add, divide, multiply, subtract)
suma_array = np.add(array_aleatorio_1, array_aleatorio_2)
suma_array

array([[11, 17,  5],
       [ 8,  7,  2]])

In [34]:
#Por ejemplo un array "ventas" con las ventas de 12 meses
ventas = np.random.randint(0,1000, (5,12))
print(ventas)
print("----------")

[[459 773   7  37   7  20  78 601 152 298 805 779]
 [894 579 127 154 770 544 351 454 563   1 106 381]
 [545 947 800 270 274 613 649 476 827 698 445  85]
 [273 853 160 913 577 491 803 791 875 537 466 862]
 [807 313 192 827 250 287 543  60  66 587 105  41]]
----------


###Analisis estadístico descriptivo

In [41]:
media_ventas = np.mean(ventas)
media_ventas


np.float64(454.1333333333333)

In [40]:
#media ventas 1º comercial
media_ventas_comercial1 = np.mean(ventas[0])
media_ventas_comercial1

np.float64(334.6666666666667)

In [39]:
media_ventas_totales = np.median(ventas)
media_ventas_totales

np.float64(471.0)

In [42]:
minimo = np.min(ventas)
minimo

np.int64(1)

In [43]:
desviacion_std = np.std(ventas)
desviacion_std

np.float64(294.7443223465985)

In [46]:
ventas_superiores_media = np.where(ventas > media_ventas)
ventas_superiores_media
#muestra las posiciones

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 4, 4, 4, 4]),
 array([ 0,  1,  7, 10, 11,  0,  1,  4,  5,  8,  0,  1,  2,  5,  6,  7,  8,
         9,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  3,  6,  9]))

In [47]:
print(media_ventas)
ventas

454.1333333333333


array([[459, 773,   7,  37,   7,  20,  78, 601, 152, 298, 805, 779],
       [894, 579, 127, 154, 770, 544, 351, 454, 563,   1, 106, 381],
       [545, 947, 800, 270, 274, 613, 649, 476, 827, 698, 445,  85],
       [273, 853, 160, 913, 577, 491, 803, 791, 875, 537, 466, 862],
       [807, 313, 192, 827, 250, 287, 543,  60,  66, 587, 105,  41]])

In [49]:
#Random de precios
precios = np.random.randint(0,1000, (5,12))

array([[ 80,  45, 515, 190, 489, 132, 353, 641, 148, 145, 244, 565],
       [720, 686, 130, 790,  77, 175, 836, 863, 996, 150, 388, 457],
       [118,  83, 646, 556, 860, 343, 628, 401, 352, 674, 851, 851],
       [798,  55, 639, 190, 672, 397, 992, 612, 958, 373, 893, 391],
       [973, 950, 747, 707, 240, 689, 314, 346, 428, 137, 276, 986]])

In [50]:
cambios_por_mes = np.diff(precios)
cambios_por_mes

array([[ -35,  470, -325,  299, -357,  221,  288, -493,   -3,   99,  321],
       [ -34, -556,  660, -713,   98,  661,   27,  133, -846,  238,   69],
       [ -35,  563,  -90,  304, -517,  285, -227,  -49,  322,  177,    0],
       [-743,  584, -449,  482, -275,  595, -380,  346, -585,  520, -502],
       [ -23, -203,  -40, -467,  449, -375,   32,   82, -291,  139,  710]])

In [51]:
media_cambios = np.mean(cambios_por_mes)
media_cambios

np.float64(10.2)

In [52]:
#Crear lista
lista_python = list(range(100))
arrange_np = np.arange(100)

In [55]:
star_time_py = time.time()
end_time_py = time.time()
tiempo_py = end_time_py - star_time_py
print(star_time_py)
print(end_time_py)



1744138001.0928369
1744138001.0928695
